language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '8'
install:
  - npm install -g codecov
  - npm install -g angular-cli
script:
  - npm run test
  - npm run report-coverage
after_success:
  - npm run packagr
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
